version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./src/test/resources/init-db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root